#!/bin/sh

DIR=$(dirname $0)

#
# This script sorts paje trace files generated by StarPU
#

##############################
# Parameters                 #
##############################
INPUTFILE=${1:-}
if [ -z "$INPUTFILE" ]; then echo "Error: <paje.trace> is empty"; exit; fi

##############################
# Core                       #
##############################
LC_ALL=C zgrep -v -e '^\(\(\(2\|3\|10\|11\)\>\)\)' $INPUTFILE
LC_ALL=C zgrep -e '^\(\(\(2\|3\|10\|11\)\>\)\)'  $INPUTFILE | sort -S 50% --parallel=4 -T . -s -V --key=2,2
